### ISSUE TITLE
sshd failed to start

### ISSUE THREAD

**Issue by Guanran928** [WilliButz/preservation#4]
After I deployed a NixOS machine with Disko and Preservation, sshd.service failed after booting up.

![image](https://github.com/user-attachments/assets/7c0fc63a-ca30-4c83-94f7-67a2cd14a485)
![image](https://github.com/user-attachments/assets/1ab5a70a-4694-43d6-8d67-b373bb158361)

/etc/ssh/ssh_host_* are empty files, bind mounted from /persist.

disko config: https://pb.ny4.dev/JQxPwa.nix
preservation config: https://pb.ny4.dev/r5DtFb.nix

**Comment by WilliButz** [comment]
I cannot confirm this issue from any of my hosts, but I'd be happy to take a look at the config. Could you please provide your config in a less obscure fashion?

For example  in a markdown code block (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks), or via https://gist.github.com

**Comment by Guanran928** [comment]
Here's my entire flake, the machine that I'm facing this issue is sin0:
https://git.ny4.dev/nyancat/flake/src/branch/master/hosts/vultr

I'm not too sure what's going on, this issue appears after every deploy.

![image](https://github.com/user-attachments/assets/827a5759-6f99-4397-b1eb-93fe11829132)

**Comment by WilliButz** [comment]
Oh I see, it is caused by the bind-mounts. The log messages from the journal would have been helpful :)

Try setting both `how = "symlink"` and `configureParent = true` for the key files in preservation like so:

```nix
preservation.preserveAt."/persist".files = [
  { file = "/etc/ssh/ssh_host_rsa_key"; how = "symlink"; configureParent = true; }
  { file = "/etc/ssh/ssh_host_ed25519_key"; how = "symlink"; configureParent = true; }
];
```
