### ISSUE TITLE
Bind-mounting `/nix` from preserved storage creates ordering cycle with etc overlay

### ISSUE THREAD

**Issue by mjm** [WilliButz/preservation#5]
I recently started trying to switch to use this project instead of impermanence, and I've hit an awkward snag with how it uses tmpfiles to set up the directories.

Basically, if I try to enable the etc overlay in NixOS (`system.etc.overlay.enable = true;`), then the fact that `/sysroot/etc` now depends on `/sysroot/nix/store` being mounted creates a cycle if `/sysroot/nix` is one of the bind mounts I'm creating via preservation. The cycle looks like this:

/sysroot/etc -> /sysroot/nix -> systemd-tmpfiles-setup-sysroot.service -> initrd-fs.target -> /sysroot/etc

If I wasn't using the etc overlay, it would break the first connection (and the last) and break the cycle. If I wasn't mounting `/nix` from `/persist/nix`, it would break the second connection and break the cycle. But by using these two things together, combined with the dependencies that preservation puts on tmpfiles for its bind mounts, creates this cycle.

Of course I could disable the etc overlay, it is experimental after all. Or I could bind mount `/nix` manually (without preservation) or otherwise remove the mounts dependency on tmpfiles (I think this bind mount will work without it?). But I figured I should report the issue regardless.

Thanks for the project!

**Comment by mjm** [comment]
Just wanted to confirm that doing this:

```nix
  fileSystems."/nix" = {
    device = "/persist/nix";
    options = [
      "bind"
      "X-fstrim.notrim"
    ];
  };
```

instead of including `{ directory = "/nix"; inInitrd = true; }` in the list of preservation directories does eliminate the cycle and makes booting work correctly, by nature of avoiding having `/sysroot/nix` depend on tmpfiles.

**Comment by ElvishJerricco** [comment]
My initial impression is that the relationship between tmpfiles and file systems is wrong here. It seems to me like tmpfiles is used to create symlinks and change permissions / ownership, which is fine. But all FS mounting should be happening first; there shouldn't be custom mount units ordered after tmpfiles. The bind mounts can just go in `fileSystems` (i.e. `fstab`), and tmpfiles can just come after `initrd-fs` / `local-fs` as usual. Should be totally fine, doesn't need custom mount units, and resolves this sort of cycle.

**Comment by WilliButz** [comment]
@mjm placing the /nix/store on the same filesystem as the persistent preservation target is not something I had considered so far, not sure if I should. I'm also using the etc overlay, but my nix store resides on a subvolume that has a regular entry in `fileSystems`, thereby avoiding the issue as @ElvishJerricco described.

**Comment by WilliButz** [comment]
>  It seems to me like tmpfiles is used to create symlinks and change permissions / ownership, which is fine. But all FS mounting should be happening first; there shouldn't be custom mount units ordered after tmpfiles.

@ElvishJerricco I'm not quite sure if this remark is only about the issue here with using preservation's mount units for the store filesystem, or generally about the approach taken in this project?

**Comment by mjm** [comment]
I don't think it's particularly unusual to have the nix store be on the preservation target. Some of my servers are like this because when I wanted to start using impermanence, it was the easiest way to migrate an existing system to it (you just move the existing `/` filesystem to `/persist` and then bind mount `/nix` with impermanence and everything works). Here is the filesystem configuration for such a machine https://git.midna.dev/mjm/nix-config/-/blob/main/hosts/megaera/default.nix?ref_type=heads#L13-39

I do think @ElvishJerricco's remark is about tmpfiles and filesystem mounts in general. We were discussing it a bit on Matrix. We weren't sure why the tmpfiles setup was needed before the mounts, since systemd will handle creating the mountpoints before mounting, so tmpfiles could be used afterwards to set permissions without issues. But maybe there's something we're missing here?

**Comment by WilliButz** [comment]
I'm definitely open to exploring the approach of creating mounts first, where systemd creates parents implicitly and then applying permissions + creating symlinks afterwards. Unless I'm missing something, that shouldn't require a change of the user-facing part of the module

**Comment by mjm** [comment]
I agree, I think it would only be an internal change, nothing API changing.

**Comment by WilliButz** [comment]
Oh, forgot to mention it in this issue as well: I changed the ordering of bind-mounts and tmpfiles in 97104c042dfa36e24659db05976409294d774ee5

(only mentioned it here https://github.com/WilliButz/preservation/pull/3#issuecomment-2441844271)

**Comment by mjm** [comment]
Yup, just switched all my machines back to mounting `/nix` through preservation rather than `fileSystems` and no issues that I can see.
