### ISSUE TITLE
persisting /etc/machine-id does not work

### ISSUE THREAD

**Issue by WilliButz** [WilliButz/preservation#6]
In case someone runs into this issue:

With recent upstream NixOS changes the handling of /etc/machine-id changed.
Currently another change is necessary upstream, i.e. the file needs to be created with content `uninitialized\n` and on a setup with preservation something like the following needs to be done to properly preserve the machine-id across reboots. I'm not yet sure how to handle the necessary config change for the commit service.

  ```nix
  {
    preservation.preserveAt."/state".files = [
      { file = "/etc/machine-id"; inInitrd = true; how = "symlink"; }
    ];

    systemd.services.systemd-machine-id-commit = {
      unitConfig.ConditionPathIsMountPoint = [
        "" "/state/etc/machine-id"
      ];
      serviceConfig.ExecStart = [
        "" "systemd-machine-id-setup --commit --root /state"
      ];
    };
  }
```
Note that it is no longer possible to use the default behavior (i.e. `how == "bindmount"`) to preserve machine-id, using a symlink instead works.
See https://github.com/NixOS/nixpkgs/pull/351151#issuecomment-2440122776

**Comment by r-vdp** [comment]
Cool, I'll give that a try, thanks for your work on this!

**Comment by WilliButz** [comment]
Documented and tested in 2788945ae61ebeb37b0fba222d0f78a63cf00df1 and b8f8a137d9e28ba3166b956451d2cea184533962
