### ISSUE TITLE
.mount are stopped on nixos-rebuild switch, crashing the system

### ISSUE THREAD

**Issue by andrevmatos** [WilliButz/preservation#7]
I tried migrating from impermanence, everything was working fine at boot, but as soon as I tried to do a `nixos-rebuild switch` (even with no changes to the flake), on activation, all `.mount` services created by preservation were stopped, failing the switch and rendering the system quite unusable until next reboot (things like journal complaining logs were rotated and showing nothing, etc).

Any idea what may be causing this?

**Comment by r-vdp** [comment]
Could you nix-diff the system closures, the one you switched from and the the one you switched to?
I'm regularly switching my laptop to a new config and I haven't encountered this.

**Comment by andrevmatos** [comment]
Oh, sorry for the noise: I just realized there was some issue with the boot entry registration: I usually did `switch --flake .. --target-host ..` on my main machine, but noticed that the generation was not being bumped; syncing the flake and switching locally fixed it for me, and new switches on top of the (now properly booted) preservation didn't stop the mounts.
